### ISSUE TITLE
[Maquetacion & Implementacion] Listado de suscripciones

### ISSUE THREAD

**Issue by JoseScap** [JoseScap/GymManagementApp#15]

**Comment by FranprzDev** [comment]
Para la suscripción
- Nombre completo
- Tipo de Suscripción (TIpo)
- Fecha Inicio y Fecha Fin
- Monto ($)
- Método de Pago

**Comment by FranprzDev** [comment]
Cabeceras de la tabla

Nombre completo | Tipo | Desde | Hasta | Monto | Medio de pago

acotaciones:
- Desde y Hasta deben parsearse para tener un formato argentino y se debe despreciar el time(hora, minuto, segundo)... lo que esta en la db es formato "dateFrom": "2024-08-02T03:00:00.000Z",
- Tipo debe ser un badge similar a la tabla de miembros
- Tipo en terminos de codigo es status, pero de cara al usuario sera de nombre Tipo
- Medio de pago debe ser un badge como Tipo pero mostrar iconos acordes a medios de pago, tal vez efectivo billetes y transferencia un banco
