### ISSUE TITLE
[Refactor] Errores en BreadCrumbs.

### ISSUE THREAD

**Issue by FranprzDev** [JoseScap/GymManagementApp#28]
Hay que definir como haremos los breadcrumbs.
Este es el de "Nueva Suscripción"

![Image](https://github.com/user-attachments/assets/d2e6bcbe-68e6-4fb5-a9a6-68583e8cae52)

Pero en cambio, el de la lista de socios es el siguiente:

![Image](https://github.com/user-attachments/assets/383282cb-6b48-45da-999d-58dcffd09448)

**Comment by FranprzDev** [comment]
En mi caso particular, creo que el primero es mejor. Y que quedaría más claro donde está parado el usuario, pero queda a ver como lo defínimos.

**Comment by JoseScap** [comment]
@FranprzDev entiendo tu punto y me parece correcto. Avanzar con la tarea en el momento que se pueda.

PD: Cuando se encuentren refactors, mejoras o mas de este tipo no usar el apartado [Bug]... Usar **[Refactor]** si es una mejora estetica pero no afecta la performance de la aplicacion. En caso que sea algo que mejore la app en aspectos tecnicos usar [Improve]
